Update security-scan.yml

diff --git a/.github/workflows/security-scan.yml b/.github/workflows/security-scan.yml
--- a/.github/workflows/security-scan.yml
+++ b/.github/workflows/security-scan.yml
@@ -27,6 +27,8 @@ jobs:
         run: |
           for url in $URLS; do
           sanitized_url=$(echo "$url" | sed -E 's|https?://||g' | tr -cd '[:alnum:]_')
+          echo "Running ZAP Baseline Scan for: $url"
+          echo "Sanitized filename: zap_baseline_report_${sanitized_url}.json"
           docker run --rm -v $(pwd):/zap/wrk -t zaproxy/zap-stable zap-baseline.py -t $url -J zap_baseline_report_$sanitized_url.json
           done
 
@@ -34,7 +36,9 @@ jobs:
         run: |
           for url in $URLS; do
           sanitized_url=$(echo "$url" | sed -E 's|https?://||g' | tr -cd '[:alnum:]_')    
-          docker run --rm -v $(pwd):/zap/wrk -t zaproxy/zap-stable zap-full-scan.py -t $url -J zap_full_report_$sanitized_url.json
+          echo "Running ZAP full Scan for: $url"
+          echo "Sanitized filename: zap_fullscan_report_${sanitized_url}.json"
+          docker run --rm -v $(pwd):/zap/wrk -t zaproxy/zap-stable zap-full-scan.py -t $url -J zap_full_report_$sanitized_url.json || echo "ZAP scan failed for $url"
           done
 
       - name: Upload Reports as Artifacts
